# Generated by Django 5.2.6 on 2025-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_shop_discount_harvest_alter_shop_discount_kazi'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
