# Generated by Django 5.2.6 on 2025-10-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_invoice_discount_percent_invoice_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_type',
        ),
    ]
