# Generated by Django 5.2.7 on 2026-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_productstockhistory_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockhistory',
            name='challan_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
