# Generated by Django 5.2.6 on 2025-10-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='discount',
        ),
    ]
