# Generated by Django 5.2.6 on 2025-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_shop_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discount_harvest',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='discount_kazi',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
