# Generated by Django 5.2.6 on 2025-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shop_discount_harvest_shop_discount_kazi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discount_harvest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='discount_kazi',
            field=models.IntegerField(),
        ),
    ]
