# Generated by Django 5.2.6 on 2025-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
