# Generated by Django 5.2.7 on 2025-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invoice_discount_amount_invoice_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discount_harvest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='discount_kazi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
