# Generated by Django 5.2.7 on 2026-01-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_shop_discount_harvest_alter_shop_discount_kazi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_stock', models.IntegerField()),
                ('added_stock', models.IntegerField()),
                ('current_stock', models.IntegerField()),
                ('tp_price', models.IntegerField()),
                ('total_stock_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.product')),
            ],
        ),
    ]
