# Generated by Django 5.2.7 on 2026-01-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productstockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockhistory',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand'),
        ),
    ]
